#!/usr/bin/env python
# START HELP
# this is an example of a simple script written in python.
# END HELP
import sys
# when attempting to complete a variable,
# --complete will be passed, with the full argument set.
# for example, 
# $ cb file_example foo a --complete
# will pass all arguments (the "a" should be autocompleted.)
if sys.argv[-1] == "--complete":
    sys.stdout.write("file autocomplete example")