#!/usr/bin/env bash
# read-from-root provides an example of reading a file relative
# to the root directory of the tome root directory.
#
# tome provides a "_TOME_SCRIPTS_ROOT" environnment variable, which
# points to the root directory of the scripts direcory tome was
# invoked with.
cat "$TOME_SCRIPTS_ROOT"/.foo