# Credit: https://www.qovery.com/blog/how-to-make-rust-multi-arch-release-easy/
project_name: tome

# before:
#   hooks:
#   - curl https://gist.githubusercontent.com/zph/032671320bb222b43719c2879f1b9f12/raw/56f1c78834c313e5c2f107a76bbed1c6cc510f8e/goreleaser.go > goreleaser.go
builds:
  - main: goreleaser.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: tome
    hooks:
      post:
        - ./scripts/goreleaser_hook.sh {{ .Arch }} {{ .Os }} {{ .ProjectName }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: tome
    goarm: 6
    tap:
      owner: zph
      name: tome
    url_template: "https://github.com/zph/tome/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Zander Hill
      email: elegant.sock3832@xargs.io
    folder: pkg/brew
    homepage: "https://github.com/zph/tome"
    description: "CLI Wrapper Tool for Turning a Folder of Scripts into an SDK"
    skip_upload: false
