[package]
name = "tome-scripts"
version = "0.12.3"
authors = ["Yusuke Tsutsumi <yusuke@tsutsumi.io>"]
edition = "2018"
license = "MIT"
description = "Turn directories of shell scripts into full-blown CLIs"
readme = "README.md"
repository = "https://github.com/toumorokoshi/tome"

[lib]
name = "tome"
path = "src/lib.rs"

[[bin]]
name = "tome"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
ignore = "0.4.25"
lazy_static = { version = "1.4.0" }

[dev-dependencies]
rstest = "0.12.0"
