[package]
name = "tome"
version = "0.1.0"
authors = ["Yusuke Tsutsumi <yusuke@tsutsumi.io>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = { version = "3.0.7", features = ["derive"] }
lazy_static = { version = "1.4.0" }


[dev-dependencies]
rstest = "0.12.0"
