[package]
name = "tome"
version = "0.11.1"
authors = ["Yusuke Tsutsumi <yusuke@tsutsumi.io>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
lazy_static = { version = "1.4.0" }

[dev-dependencies]
rstest = "0.12.0"
