[package]
name = "tome"
version = "0.1.0"
authors = ["Yusuke Tsutsumi <yusuke@tsutsumi.io>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = "3.0.0-beta.2"
clap_generate = { repo = "https://github.com/clap-rs/clap/tree/master/clap_generate" }
log = "*"
env_logger = "*"

[dev-dependencies]
