[workspace]
# Enable publishing to crates.io
publish = true
# Disable public API breaking change checks against crates.io
semver_check = false
# Enable automatic creation of GitHub releases with changelog notes
git_release_enable = true
