#!/usr/bin/env bash
# COMPLETE
# showing a case of returning deeper completes
if [[ "$1" == "--complete" ]]; then
    shift
    if [[ $# -gt 0 ]]; then
        echo "completed with: $*"
    else
        echo "--bar1 --bar2 --not-bar"
    fi
    exit
fi
echo "COMMAND: baz $*"